part of 'theme.dart';

/// Generated by Forui CLI.
///
/// Icon tokens for the generated theme.
FIcons _icons() => FIcons(
  arrowLeft: const _Icon(HugeIcons.strokeRoundedArrowLeft01),
  calendar: const _Icon(HugeIcons.strokeRoundedCalendar03),
  check: const _Icon(HugeIcons.strokeRoundedTick02),
  chevronDown: const _Icon(HugeIcons.strokeRoundedArrowDown01),
  chevronLeft: const _Icon(HugeIcons.strokeRoundedArrowLeft01),
  chevronRight: const _Icon(HugeIcons.strokeRoundedArrowRight01),
  chevronUp: const _Icon(HugeIcons.strokeRoundedArrowUp01),
  chevronsUpDown: const _Icon(HugeIcons.strokeRoundedUnfoldMore),
  circleAlert: const _Icon(HugeIcons.strokeRoundedAlertCircle),
  clock4: const _Icon(HugeIcons.strokeRoundedClock01),
  ellipsis: const _Icon(HugeIcons.strokeRoundedMoreHorizontal),
  error: const _Icon(HugeIcons.strokeRoundedAlertCircle),
  eye: const _Icon(HugeIcons.strokeRoundedView),
  eyeClosed: const _Icon(HugeIcons.strokeRoundedViewOff),
  gripHorizontal: const _Icon(HugeIcons.strokeRoundedDragDropHorizontal),
  gripVertical: const _Icon(HugeIcons.strokeRoundedDragDropVertical),
  loader: const _Icon(HugeIcons.strokeRoundedLoading03),
  loaderCircle: const _Icon(HugeIcons.strokeRoundedLoading03),
  loaderPinwheel: const _Icon(HugeIcons.strokeRoundedLoaderPinwheel),
  search: const _Icon(HugeIcons.strokeRoundedSearch01),
  userRound: const _Icon(HugeIcons.strokeRoundedUserCircle),
  x: const _Icon(HugeIcons.strokeRoundedCancel01),
);

class _Icon implements FIcon {
  final List<List<dynamic>> icon;

  const _Icon(this.icon);

  @override
  Widget call(BuildContext _, {String? semanticsLabel}) =>
      HugeIcon(icon: icon, size: null);

  // HugeIcons' constants are const lists, so identity is sufficient.
  @override
  bool operator ==(Object other) =>
      identical(this, other) || other is _Icon && identical(icon, other.icon);

  @override
  int get hashCode => identityHashCode(icon);
}
