part of 'theme.dart';

// ignore_for_file: avoid_redundant_argument_values

/// Generated by Forui CLI.
///
/// Style tokens and theme extensions for the generated theme.
FStyle _style({
  required FColors colors,
  required FTypography typography,
  required bool touch,
}) {
  const borderRadius = FBorderRadius(
    xs2: .all(.circular(3.0)),
    xs: .all(.circular(4.0)),
    sm: .all(.circular(6.0)),
    md: .all(.circular(7.0)),
    lg: .all(.circular(10.0)),
    xl: .all(.circular(13.0)),
    xl2: .all(.circular(16.0)),
    xl3: .all(.circular(19.0)),
    pill: .all(.circular(100.0)),
  );
  return FStyle(
    formFieldStyle: .inherit(
      colors: colors,
      typography: typography,
      touch: touch,
    ),
    focusedOutlineStyle: FFocusedOutlineStyle(
      color: colors.primary,
      borderRadius: borderRadius.md,
    ),
    sizes: FSizes.inherit(touch: touch),
    iconStyle: IconThemeData(
      color: colors.foreground,
      size: typography.body.lg.fontSize,
    ),
    tappableStyle: FTappableStyle(),
    borderRadius: const FBorderRadius(
      xs2: .all(.circular(3.0)),
      xs: .all(.circular(4.0)),
      sm: .all(.circular(6.0)),
      md: .all(.circular(7.0)),
      lg: .all(.circular(10.0)),
      xl: .all(.circular(13.0)),
      xl2: .all(.circular(16.0)),
      xl3: .all(.circular(19.0)),
      pill: .all(.circular(100.0)),
    ),
    borderWidth: 1,
    pagePadding: const .symmetric(vertical: 8, horizontal: 12),
    shadow: const [
      BoxShadow(color: Color(0x0d000000), offset: Offset(0, 1), blurRadius: 2),
    ],
    extensions: const [AppStyle()],
  );
}

/// Provides convenient access to theme extensions on [FStyle].
///
/// ```dart
/// final cardRadius = context.theme.style.app.cardRadius; ✅
///
/// // Alternatively, you can create a getter to access extension fields directly.
/// final cardRadius = context.theme.style.cardRadius; ✅
///
/// final cardRadius = context.theme.style.extension<AppStyle>().cardRadius; ❌
/// ```
extension FStyleExtensions on FStyle {
  AppStyle get app => extension<AppStyle>();
}

/// Custom style tokens unique to your app.
///
/// Add your fields below, then implement [copyWith], [lerp], [==], and [hashCode].
/// See https://api.flutter.dev/flutter/material/ThemeExtension-class.html.
class AppStyle extends ThemeExtension<AppStyle> {
  // TODO: add your style fields here:
  // final double cardRadius;

  const AppStyle();

  @override
  AppStyle copyWith() => const AppStyle();

  @override
  AppStyle lerp(covariant AppStyle? other, double t) {
    if (other == null) {
      return this;
    }
    return const AppStyle();
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppStyle && runtimeType == other.runtimeType;

  @override
  int get hashCode => runtimeType.hashCode;
}
